### ISSUE TITLE
 (object 'nLev' not found) on VIM regressionImp function (Used for categorical var)

### ISSUE THREAD

**Issue by varvanih** [statistikat/VIM#32] opened 2019-11-28 05:06 UTC
Hello,

I tried to use the regressionImp function for a data set with only categorical variables (attached to this message). I encountered the "object 'nLev' not found" error. I tried to change the input arguments including the "formulas" used in the function, but it did not help.

My R version is 3.6.1 run on Windows 10 64bit.

Any help is really appreciated.

Thanks,
Farahani

[TTTTEG_AE_1.xlsx](https://github.com/statistikat/VIM/files/3899916/TTTTEG_AE_1.xlsx)

**Comment by GregorDeCillia** [comment] 2020-04-15 13:41
Repex

```r
dataset <- readxl::read_excel("TTTTEG_AE_1.xlsx", col_names = FALSE)
names(dataset) <- LETTERS[1:9]
VIM::regressionImp(A ~ B, dataset)
#> Error in regressionImp_work(formula = formula, data = data, family = family,  : 
#>   object 'nLev' not found
```

`nLev` is attempted to be read in `regressionImp_work`, but was not assigned previously https://github.com/statistikat/VIM/blob/5e4b96cc03b64d27323ab9b263229de1cb4ebb38/R/regressionImp.R#L134

I'll work on a proper fix for this in the near future. In the meantime. a simple workaround is to change the type of the response variable from a character to a factor prior to calling the imputation method

```r
dataset$A <- as.factor(dataset$A)
dataset_imputed <- VIM::regressionImp(A ~ B, dataset)
#> There still missing values in variable A . Probably due to missing values in 
#> the regressors.
table(dataset$A, useNA = "always")
#> 
#>    b    o    x <NA> 
#>  204  331  411   12 
table(dataset_imputed$A, useNA = "always")
#> 
#>    b    o    x <NA> 
#>  204  331  419    4 
```

We can see that 8 values were imputed with the value `"x"`. The remaining missings are expected because of missings in the regressor variable `B`.

**Closed** 2020-04-15 14:08 UTC
