### ISSUE TITLE
hotdeck Imputation fails or is incorrect when first lines has missing

### ISSUE THREAD

**Issue by poidstotal** [statistikat/VIM#30] opened 2019-02-04 01:53 UTC
Hi I ran into an issue when using the hotdeck imputation. the last observation carried forward method fails when the first contain missing.  Actually VIM will return 1 and not an error message, which make it impossible de detect for numeric variable. The issue is noticeable only when you try to impute a character type variable.

**Comment by alexkowa** [comment] 2019-02-04 11:20
Could you please provide some example, my minimalistic example which I just added to the hotdeck tests worked:
`df2 <- data.frame(unit_id=c(NA,101:104), state=rep("NSW",5), wages01=c(NA,NA,NA,2434,229305),r=runif(5))

test_that("hotdeck should fill all values including the first one", {
  df.out <- hotdeck(df2, variable=c("unit_id","wages01"))
  expect_identical(df.out,na.omit(df.out))
})

test_that("hotdeck should fill all values including the first one - domain_var", {
  df.out <- hotdeck(df2, variable=c("unit_id","wages01"), domain_var="state")
  expect_identical(df.out,na.omit(df.out))
})

test_that("hotdeck should fill all values including the first one - ord_var", {
  df.out <- hotdeck(df2, variable=c("unit_id","wages01"), ord_var="r")
  expect_identical(df.out,na.omit(df.out))
})`

**Comment by poidstotal** [comment] 2019-02-05 12:52
it seems fine from the example above. But there are still error when I used the process on my data. The error I receive is:
Warning message:
In `[<-.factor`(`*tmp*`, TFindex, value = 1) :
  invalid factor level, NA generated

I understand this as a value = 1 is being sent for a factor variable.

**Comment by poidstotal** [comment] 2019-02-05 12:53
And thank for looking into this.

**Comment by alexkowa** [comment] 2019-02-07 11:44
Unfortunately, I cannot reproduce it. So I close this. Please reopen if you find an example you can share.

**Closed by alexkowa** 2019-02-07 11:44 UTC
